### ISSUE TITLE
Error in self$model$get_scores(effect_i = effect_i, component = component) :    object 'PC' not found

### ISSUE THREAD

**Issue by MuyaoXi9271** [andjar/ALASCA#10]
Hi developer,

I got the ALASCA model successfully but accidentally removed the log file. I met the error as shown in the title when I ran `plot(ALASCA_model, component = c(1,2), type = "effect") `

I appreciate any help you could provide.

Best,
Muyao

**Comment by andjar** [comment]
Hi @MuyaoXi9271,

Thanks for reporting this issue. I am not able to replicate the error. What version of ALASCA are you using? What settings do you use?

Best,
Anders

**Comment by MuyaoXi9271** [comment]
Hi Anders,

The version I used is 1.0.14.

`ALASCA_model <- 
  ALASCA(df_l,
         formula = value ~ visit*group + (1|subject),
         scale_function = "sdall",
         validate = TRUE,
         filepath = paste0(path_outputs$POS, "/ALASCA"),
         save = TRUE)`

Thanks for your quick reply.

Best,
Muyao

**Comment by andjar** [comment]
Hi,

Thank you for the additional information. I am still unable to reproduce the error using the Example 2 dataset in our paper and your settings. Is `visit` a factor variable? Do you get any output with `ALASCA_model$get_scores(component = c(1,2))`?

Best,
Anders

**Comment by MuyaoXi9271** [comment]
Hi Anders,

I get the same error. What else can I check also?

Best,
Muyao

**Comment by andjar** [comment]
You can have a look at the score data table itself with `ALASCA_model$ALASCA$score` which contains all the PCs calculated

**Comment by MuyaoXi9271** [comment]
![image](https://github.com/andjar/ALASCA/assets/87710342/ad705c52-bec4-4bcb-aaba-fa24b2d61197)

I can get the data table after running `ALASCA_model$ALASCA$score` as shown in the image above.

Best,
Muyao

**Comment by andjar** [comment]
Strange! Can you check that it is indeed a data table? `is.data.table(ALASCA_model$ALASCA$score[[1]])`

So, the issue here is that - with `data.table` - we can select the appropriate rows with `self$ALASCA$score[[effect_i]][PC %in% component]` (where `self` is the model object) - this is the code in the `get_scores` function that throws the error. But there is something preventing this selection to work. We can, however, see that the data table exists and has a column called `PC`

**Comment by MuyaoXi9271** [comment]
Hi Anders,

It is not a data table. And I have changed it to the data table. And I noticed that when I select components as the codes you mentioned, it choses the whole table instead of PC, as shown in the figure below.
![image](https://github.com/andjar/ALASCA/assets/87710342/baf00ba4-3124-43ba-9012-927085540947)

Is it normal?

Best,
Muyao

**Comment by MuyaoXi9271** [comment]
Hi Ander,

It works now.

Thanks for your help 

Best,
Muyao
