### ISSUE TITLE
 object of type 'closure' is not subsettable

### ISSUE THREAD

**Issue by CM-07** [andjar/ALASCA#11]
Hi!
I am using an untargeted metabolomics data and I have around 5000 features (variables), two time points and 44 subjects, and 4 Treatment groups.
I am getting following error:
 mod <- ALASCA(
+   df = final_result,
+   formula = Value ~ Time + (1 | Subject),scale_function = "sdt1")
INFO  [2024-03-11 13:22:11] Initializing ALASCA (v1.0.15, 2024-02-07)
WARN  [2024-03-11 13:22:11] Guessing effects: `Time`
INFO  [2024-03-11 13:22:11] Will use linear mixed models!
INFO  [2024-03-11 13:22:11] Will use Rfast!
WARN  [2024-03-11 13:22:11] The `Time` column is used for stratification
INFO  [2024-03-11 13:22:11] Scaling data with sdt1 ...
Error in value[get(self$effect_terms[[1]]) == self$get_ref(self$effect_terms[[1]])] : 
object of type 'closure' is not subsettable

I have some values with 0's but they are not missing values. Otherwise I do not find why I would see this error.
Is it related to having many variable names ? 
Thank you!

**Comment by CM-07** [comment]
I got it solved by changing the name of the variables.

**Comment by andjar** [comment]
Thanks for reporting this issue and describing how you solved it. Please feel free to reach out again if there are more problems!
