### ISSUE TITLE
Plotting not working in example in "Getting Started".

### ISSUE THREAD

**Issue by joseabernal** [andjar/ALASCA#14]
I am trying to run the example code https://andjar.github.io/ALASCA/articles/ALASCA.html. While ALASCA runs, I am unable to use the 'plot' command:

> plot(res, component = c(1,2), type = 'effect')
INFO  [2024-08-07 17:27:27] Effect plot. Selected effect (nr 1): `time`. Component: 1 and 2.
Error in vapply(columns, FUN = function(column) { : 
  values must be length 1,
 but FUN(X[[1]]) result is length 0

Do you happen to know why this is happening?

**Comment by andjar** [comment]
Hi @joseabernal 

Thanks for getting in touch, sorry for my late reply. I forgot to push v1.0.17 earlier this year, with a small bug fix related to plotting. I was not able to reproduce the error in that version. Could you please try to upgrade to v1.0.17 and see if that fixes the error? Thanks!

Best,
Anders
