### ISSUE TITLE
Error in ALASCA with scale_function = "none"

### ISSUE THREAD

**Issue by CynFP** [andjar/ALASCA#6]
Hi Anders!
I continue testing the fantastic ALASCA package. This time I am trying a previously normalized and standardized database, so when using the ALASCA function, I used the condition scale_function = "none". The function starts running without a problem, but when it reaches the scaling, it generates an error. I tried with the database of Example 2, and the same thing happened:

> if (!file.exists(here("output/ex2.part1A/validation_IDs.csv"))) {
+   mod <- ALASCA(
+     df,
+     formula = value ~ time + time:group + (1|ID),
+     wide = TRUE,
+     separate_effects = TRUE,
+     equal_baseline = TRUE,
+     scale_function = "none",
+     filepath = here("output","ex2.part1A"),
+     filename = "model.ex2.part1",
+     n_validation_runs = 1000,
+     validate = TRUE,
+     save = TRUE,
+     validation_method = "bootstrap",
+     save_validation_ids = TRUE
+   )
+   
+   flip(mod, effect = 1)
+   plot(mod, effect = c(1,2), component = 1)
+   plot(mod, effect = c(1,2), component = 2)
+   plot(mod, effect = 1, component = c(1,2), type = "2D")
+   plot(mod, effect = 2, component = c(1,2), type = "2D")
+   plot(mod, effect = 1, component = 1, type = "validation")
+   plot(mod, effect = 1, component = 2, type = "validation")
+   plot(mod, effect = 2, component = 1, type = "validation")
+   plot(mod, effect = 2, component = 2, type = "validation")
+   plot(mod, effect = 1, component = 1, type = "histogram")
+   plot(mod, effect = 2, component = 1, type = "histogram")
}
INFO  [2023-02-01 12:35:03] Initializing ALASCA (v1.0.8, 2023-01-15)
WARN  [2023-02-01 12:35:03] Guessing effects: `time` and `time:group`
INFO  [2023-02-01 12:35:03] Will use linear mixed models!
INFO  [2023-02-01 12:35:03] Will use Rfast!
INFO  [2023-02-01 12:35:03] Converting from wide to long!
INFO  [2023-02-01 12:35:03] Found 16 variables
WARN  [2023-02-01 12:35:03] The `group` column is used for stratification
WARN  [2023-02-01 12:35:03] Not scaling data...
**Error in identity() : argument "x" is missing, with no default**

According to the package, the scale_function condition can use the following options: `none`, `sdall`, `sdref`, `sdreft1`, `sdt1`. I want to corroborate if, indeed, you can work ALASCA without the scaling of the data inside the function.
Again thank you very much for your time and excellent work.

Regards,
Cynthia

> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Mexico.utf8  LC_CTYPE=Spanish_Mexico.utf8   
[3] LC_MONETARY=Spanish_Mexico.utf8 LC_NUMERIC=C                   
[5] LC_TIME=Spanish_Mexico.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.4.0     ALASCA_1.0.7      data.table_1.14.6 here_1.0.1       

loaded via a namespace (and not attached):
 [1] log4r_0.4.3      pillar_1.8.1     compiler_4.2.2   ggpubr_0.5.0     tools_4.2.2     
 [6] lifecycle_1.0.3  tibble_3.1.8     gtable_0.3.1     pkgconfig_2.0.3  rlang_1.0.6     
[11] DBI_1.1.3        cli_3.4.1        rstudioapi_0.14  withr_2.5.0      dplyr_1.0.10    
[16] generics_0.1.3   vctrs_0.5.1      gtools_3.9.4     rprojroot_2.0.3  grid_4.2.2      
[21] tidyselect_1.2.0 glue_1.6.2       R6_2.5.1         rstatix_0.7.1    fansi_1.0.3     
[26] carData_3.0-5    purrr_1.0.0      tidyr_1.2.1      car_3.1-1        magrittr_2.0.3  
[31] scales_1.2.1     backports_1.4.1  assertthat_0.2.1 abind_1.4-5      colorspace_2.0-3
[36] ggsignif_0.6.4   utf8_1.2.2       munsell_0.5.0    broom_1.0.2

**Comment by andjar** [comment]
Hi Cynthia,

Thank you for identifying another bug, I am very grateful for you finding and reporting these issues! Hopefully, this problem is now resolved in v1.0.9 - please let me know if the error persists!

Best,
Anders

**Comment by CynFP** [comment]
Hi Anders!

Thank you so much! It works perfectly.
Regards,
Cynthia

**Comment by andjar** [comment]
Perfect, Cynthia, thank you for letting me know and please continue reporting the bugs you are finding, it is very useful!

Best,
Anders
