### ISSUE TITLE
type="covars" gives error while plotting the ALASCA object

### ISSUE THREAD

**Issue by nilaycan** [andjar/ALASCA#7]
Hi Anders,

Thanks so much for implementing such a cool package, it's quite useful and versatile!

I have two Q's, **the first one** is when I try to plot the ALASCA object with "`type=covars`" argument with plot function, I always get this error with different models:

```
Error in factor(covars, levels = data_to_plot[order(loading), covars]) : 
  object 'covars' not found
```

I installed the package with `devtools::install_github("andjar/ALASCA", ref = "main")` command so it should get the latest updates, right?

Thanks in advance!
Best regards,
Nilay

**Comment by nilaycan** [comment]
I have another tiny issue I forgot to mention!

When I use the `effect = c(1, 2)` argument in a plot function, I want to keep the group starting with the letter "P" stable in the second plot to reflect the group difference (I want to keep group P stable and M changing in the second score plot of PC1). The other group starts with "M", so I ordered the input by the group column with decreasing and increasing order, it doesn't affect the plots, so I would appreciate it if you could suggest something :) Thanks!

**Comment by biga94** [comment]
I have the same problem. Also when I want to visualize specific predictions in terms of marginal means, I cannot select a specific vector of variables to visualize due to the same error. 
Noteworthy, the same error comes out using also the dataset generated from the developer on [Getting started](https://andjar.github.io/ALASCA/articles/regression.html).

**Comment by biga94** [comment]
> I have the same problem. Also when I want to visualize specific predictions in terms of marginal means, I cannot select a specific vector of variables to visualize due to the same error. Noteworthy, the same error comes out using also the dataset generated from the developer on [Getting started](https://andjar.github.io/ALASCA/articles/regression.html).

@andjar that's the other error I was mentioning in the other issues thread
