### ISSUE TITLE
Error in eigen(w1) : infinite or missing values in 'x' error when validation method is chosen

### ISSUE THREAD

**Issue by nilaycan** [andjar/ALASCA#8]
Dear Anders,

I wanted to open another issue that may help you to answer better so here you go :)

I converted my continuous age variable to a six-level continuous variable and my ALASCA model looks like:

```
my_model <- ALASCA(input,
                          value ~ time*age_factor+ (1|id),
                          separate_effects = T,
                          scale_function = "sdt1",
                     equal_baseline = T,
                     plot.loading_group_column = "type",
                     plot.loading_group_label = "Amino acid class",
                     max_PC =22, equal_baseline = T,
                     pca_function = "princomp",
                     validate=T, n_validation_runs = 90,
                     validation_method = "jack-knife")
```

So, this command works well after a couple of trials otherwise, it gives this error:

`Error in eigen(w1) : infinite or missing values in 'x' `

When I replace the validation method with "bootstrap", it fails more quicker. I tried other pca_function arguments too but jack-knife seems to work with fewer issues.

According to your benchmark in [ALASCA](https://www.frontiersin.org/articles/10.3389/fmolb.2022.962431/full) publication, jack-knife seems to have smaller CIs but the two methods do not significantly differ from each other. For example, [here](https://academic.oup.com/jcem/advance-article/doi/10.1210/clinem/dgad145/7077195) they preferred "bootstrapping" but [here](https://academic.oup.com/jcem/article/107/1/39/6371132) they used jack-knifing. But what causes this issue, why does jack-knife seem to analyze better than Bootstrap and I got this error? 

Thanks!
Best regards,
Nilay

**Comment by andjar** [comment]
Hi Nilay, sorry for my late follow up. Hopefully, you got some results?
So, this is just a guess, but the bootstrapping and jack-knifing use stratified samples, and if one of the stratification groups is small, you may end up selecting just one individual multiple times, which will produce zero variance, which is a problem. This is just a guess, there might be something else going on
