### ISSUE TITLE
Error: Mat::init()

### ISSUE THREAD

**Issue by biga94** [andjar/ALASCA#9]
Hey there,
I tried to perform an ALASCA model using a longitudinal dataset of 1260 rows and 5 columns (colnames: ID, Timepoint, Group, Variable, value).

Call for the model:
`mod <- ALASCA(df = longitudinal_data,
              formula = value ~ Timepoint*Group + (1|"Patient code"),
              scale_function = "sdt1",
              validate = TRUE,
              ignore_missing_covars = T)`

Unfortunately this error comes out:

```
INFO  [2023-10-18 11:11:14] Initializing ALASCA (v1.0.11, 2023-06-19)
WARN  [2023-10-18 11:11:14] Guessing effects: `Timepoint+Timepoint:Group+Group`
INFO  [2023-10-18 11:11:14] Will use linear mixed models!
INFO  [2023-10-18 11:11:14] Will use Rfast!
WARN  [2023-10-18 11:11:14] Converting IDs to integer values
WARN  [2023-10-18 11:11:14] The `Timepoint` column is used for stratification
WARN  [2023-10-18 11:11:14] Converting `character` columns to factors
WARN  [2023-10-18 11:11:14] Predictor variables missing for some samples! Continue with caution!
INFO  [2023-10-18 11:11:14] Scaling data with sdt1 ...
INFO  [2023-10-18 11:11:14] Calculating LMM coefficients

Error: Mat::init(): requested size is too large; suggest to enable ARMA_64BIT_WORD
```

Of course I've tried to delve into various Stackoverflow's threads withount any success.
Do you know how to deal with this error?
Best,

DB

P.S. I'm working on macOS Sonoma 14.0 on Macbook Pro 16" M1 Max

**Comment by andjar** [comment]
Hi DB, sorry for my late response. Did you find a solution? It seems strange that the `requested size is too large` for such a small dataset. I guess `(1|"Patient code")` will be `(1|ID)` in the actual code. You may try to use `use_Rfast = FALSE` to utilize `lme4::lmer()` instead

Please feel free to email me if you have a dummy dataset that reproduces the error!

**Comment by biga94** [comment]
Hi, I was able to solve the problem by... doing nothing! Next day everything worked like charms! Thanks for your suggestion, I've implemented lme4 instead of Rfast for modelling, also because I had the necessity to accompany results with statistical significance.
I've another error, but I prefer to open another issue instead of using this thread.

Thanks!!
DB
